INSERT INTO TB_PRODUTO(ID,NOME_PRODUTO,QUANTIDADE,VALOR_UNITARIO)VALUES(1,'PRODUTO AA', 100, 10.50);
INSERT INTO TB_PRODUTO(ID,NOME_PRODUTO,QUANTIDADE,VALOR_UNITARIO)VALUES(2,'PRODUTO BB', 30, 99.99);
INSERT INTO TB_PRODUTO(ID,NOME_PRODUTO,QUANTIDADE,VALOR_UNITARIO)VALUES(3,'PRODUTO XX', 20, 25.69);
INSERT INTO TB_PRODUTO(ID,NOME_PRODUTO,QUANTIDADE,VALOR_UNITARIO)VALUES(4,'PRODUTO DD', 12, 35.50);
INSERT INTO TB_PRODUTO(ID,NOME_PRODUTO,QUANTIDADE,VALOR_UNITARIO)VALUES(5,'PRODUTO KK', 30, 125.00);


